# Use of ggprism and ggsci packages

Yifan Jiang

<h1 style="color:darkred;">Overview</h1>
  <br>
  <p style="font-size:22px;">
    <strong>ggprism</strong> and <strong>ggsci</strong> can respectively set the style and color of the picture generated by ggplot. This style and color are used in a large number of papers.
  </p>
    <br>
    <h1 style="color:darkred;">Package</h1>
      <li style="font-size:22px;">library(ggprism)</li>
        <li style="font-size:22px;">library(ggsci)</li>
          <br>
          <h1 style="color:darkred;">ggprism</h1>
            <li style="font-size:22px;color:darkblue">theme_prism()</li>
              <p style="font-size:22px;">Change the style of the graph, similar to the style of the Prism software.</p>
                <li style="font-size:22px;color:darkblue">scale_color_prism(palette="colors")</li>
                  <li style="font-size:22px;color:darkblue">scale_fill_prism(palette="colors")</li>
                    <li style="font-size:22px;color:darkblue">scale_colour_prism(palette="colors")</li>
                      <p style="font-size:22px;">There are many optional color schemes to change the color of the picture, which is very convenient.</p>
                        <li style="font-size:22px;color:darkblue">scale_shape_prism()</li>
                          <p style="font-size:22px;">Shape scales that approximate those used in GraphPad Prism.</p>
                            <li style="font-size:22px;color:darkblue">scale_x_discrete(guide = "prism_bracket")</li>
                              <p style="font-size:22px;">Segment the coordinate axis.</p>
                                <li style="font-size:22px;color:darkblue">add_pvalue(data_frame)</li>
                                  <p style="font-size:22px;">Add a hypothesis test p-value to the picture</p>
                                    <h1 style="color:darkred;">ggsci</h1>
                                      <li style="font-size:22px;color:darkblue">scale_color_aaas()</li>
                                        <li style="font-size:22px;color:darkblue">scale_color_d3()</li>
                                          <li style="font-size:22px;color:darkblue">scale_color_npg()</li>
                                            <li style="font-size:22px;color:darkblue">There are too many coloring scheme to write...</li>
                                              <p style="font-size:22px;">This function can directly call the color scheme of various scientific journals, which is very beautiful and very convenient to use.</p>
                                                <br>
                                                <h1 style="color:darkred;">Example</h1>
                                                  ```{r include=FALSE}
                                                library(ggsci)
                                                library(tidyverse)
                                                library(knitr)
                                                library(ggprism)
                                                library(patchwork)
                                                kable(head(iris))
                                                ```
                                                <p style="font-size:22px;">The picture on the left does not use theme_prism, the picture on the right uses it.</p>
                                                  ```{r}
                                                p1 <- iris %>% ggplot(aes(Sepal.Length,Sepal.Width))+geom_point()
                                                p2 <- iris %>% ggplot(aes(Sepal.Length,Sepal.Width))+geom_point()+theme_prism()
                                                p1+p2
                                                ```
                                                <p style="font-size:22px;">The default coordination of ggplot and the color scheme of ggprism are respectively shown. ggprism's high-contrast color matching is very suitable for scientific research articles.</p>
```{r}
p1 <- iris %>% ggplot(aes(Sepal.Length,Sepal.Width,color=Species))+geom_point()+theme_prism()+ggtitle("Original")
p2 <- iris %>% ggplot(aes(Sepal.Length,Sepal.Width,color=Species))+geom_point()+theme_prism()+scale_color_prism(palette = "flames")+ggtitle("Flames")
p3 <- iris %>% ggplot(aes(Sepal.Length,Sepal.Width,color=Species))+geom_point()+theme_prism()+scale_color_prism(palette = "floral")+ggtitle("Floral")
p4 <- iris %>% ggplot(aes(Sepal.Length,Sepal.Width,color=Species))+geom_point()+theme_prism()+scale_color_prism(palette = "candy_bright")+ggtitle("candy_bright")
(p1+p2)/(p3+p4)
```
<p style="font-size:22px;">The image above does not use the x-axis segmentation, and the image below uses the x-axis segmentation.</p>
```{r}
p1 <- iris %>% ggplot(aes(Species,Sepal.Length))+geom_jitter(aes(shape=Species))+theme_prism()
p2 <- iris %>% ggplot(aes(Species,Sepal.Length))+geom_jitter(aes(shape=Species))+theme_prism()+scale_x_discrete(guide = "prism_bracket")+scale_shape_prism()
p1/p2
```

<p style="font-size:22px;">The picture on the right has pvalue added, and the picture on the left does not.</p>
```{r}
p1 <- iris %>% filter(Species %in% c("virginica","versicolor")) %>% ggplot(aes(Species,Sepal.Length,fill=Species))+geom_boxplot()+theme_prism()+scale_fill_prism("floral")+theme(legend.position = "none")
two.means <- tibble::tribble(
  ~group1, ~group2, ~p,     ~y.position,
  "virginica",    "versicolor",    1.866e-07, 36
)
p <- data.frame(
  group1="virginica",
  group2="versicolor",
  p.adj = 1.866e-07,
  y.position = 8
)

p2 <-  iris %>% filter(Species %in% c("virginica","versicolor")) %>% ggplot(aes(factor(Species),Sepal.Length))+geom_boxplot(aes(fill=Species))+theme_prism()+scale_fill_prism("floral")+theme(legend.position = "none")+add_pvalue(data=p)
p1+p2
```
<p style="font-size:22px;">The various color schemes of ggsci are shown below.</p>
```{r}
p1 <- iris %>% ggplot(aes(Species,Sepal.Width,color=Species))+geom_boxplot()+geom_jitter()+theme_prism()+ggtitle("Original")
p2 <-  iris %>% ggplot(aes(Species,Sepal.Width,color=Species))+geom_boxplot()+geom_jitter()+theme_prism()+scale_color_aaas()+ggtitle("AAAS")
p3 <- iris %>% ggplot(aes(Species,Sepal.Width,color=Species))+geom_boxplot()+geom_jitter()+theme_prism()+scale_color_npg()+ggtitle("NPG")
p4 <- iris %>% ggplot(aes(Species,Sepal.Width,color=Species))+geom_boxplot()+geom_jitter()+theme_prism()+scale_color_d3()+ggtitle("d3")
p5 <- iris %>% ggplot(aes(Species,Sepal.Width,color=Species))+geom_boxplot()+geom_jitter()+theme_prism()+scale_color_jama()+ggtitle("JAMA")
p6 <- iris %>% ggplot(aes(Species,Sepal.Width,color=Species))+geom_boxplot()+geom_jitter()+theme_prism()+scale_color_lancet()+ggtitle("Lancet")
(p1+p2)
(p3+p4)
(p5+p6)
```

