# Streamlit for Financial Analysis

Smaranjit Ghose and Siddhant Pravin Mahurkar

Motivation for the project:

From our previous experiences of working in Data Science teams and personal trading endeavors, we observed that there is a huge gap in the literature available for easily building useful dashboards for analysis of price of financial instruments like stocks, bonds or crypto. The internet is flooded with false promising articles on how to use Reinforcement Learning to accurately predict stock prices but there is very less material on how to actually code's customized dashboard and analyze various indicators for making a trade. Furthermore, with the rise of streamlit as a de facto app for deploying end to end machine learning applications,we saw an opportunity to bring the benefits of it for our problem of financial data visualization. Moreover, a lot of people get stuck in their work done in a JupyterNotebook or RMarkdown and fail to take it to production which is often the demand while working in a Data Science team who needs to present a MVP to their clients. Hence, we have also shown how to take the dashboard to production so that users can interact with it real time.


The Link to the Project can be found [here](https://pystockanalysis.herokuapp.com/) 

The Link to the Blog can be found [here](https://blog.smaranjitghose.com/streamlit-finance-dashboard)

The Link to the Repository can be found [here](https://github.com/smaranjitghose/PyStockAnalysis)
