# Vipul EDAV Community Contribution Kickstart R

Vipul H Harihar

This hand written notes are specially made for understanding the basics of Exploratory Data Analysis and R. This material here is a summation of my Professor Joyce's teachings in classroom lectures and R documentation files. 
I have tried to write neatly and clearly so that the reader might benefit from the notes easily, I hope it is easily understandable and legible. 
The topics involved in the notes are as follows:
1) Introduction
2) R Programming for EDAV
3) Some Fun Facts about R
4) Features of R that makes it perfect for "EDAV"
5) Application of R Programming
6) Understanding Basic Data Types in R
7a) Some Handy Functions 
7b) Vector
7c) List
7d) Factors - VERY IMPORTANT
7e) Data Frame
7f) Missing Values
8) Diagonistic Functions in R
9) Data Science Process (Visual Description)
10) What all visulizations we use in EDAV?

Please find the link to the submitted file:
https://github.com/virslaan/EDAV_Community_Contribution/blob/main/Community%20Contribution%202.pdf
